spring:
  application:
    name: terrarent
  datasource:
    url: jdbc:postgresql://dpg-d933smlaeets73b2gb00-a.virginia-postgres.render.com:5432/lodgix_db
    username: lodgix_db_user
    password: 6fJg2OzywqEXqTFbBCrybTJGjeqYZLDp
    driver-class-name: org.postgresql.Driver
  main:
    allow-circular-references: true
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: ${SPRING_MAIL_HOST:smtp.gmail.com}
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:aSuperSecretKeyForTerraRentApplicationWhichIsLongEnoughForHS256Algorithm}
      access-token-expiration: 7200000 
      refresh-token-expiration: 604800000 

bookingcom:
  api:
    base-url: ${BOOKING_COM_BASE_URL:https://demandapi-sandbox.booking.com/3.1}
    affiliate-id: ${BOOKING_COM_AFFILIATE_ID:YOUR_AFFILIATE_ID}
    token: ${BOOKING_COM_TOKEN:YOUR_API_TOKEN}

gemini:
  api:
    base-url: ${GEMINI_API_BASE_URL}
    key: ${GEMINI_API_KEY}
    model: ${GEMINI_API_MODEL:gemini-1.0}

logging:
  file:
    name: backend.log
  level:
    com.terrarent: DEBUG
    org.springframework.security: DEBUG

server:
  port: ${PORT:8081}